---
# Purpose: Add Kerberos related traits to the nodes
- name: Ensure Kerberos client tools are installed
  yum:
    name: krb5-workstation
    state: present

- name: Ensure krb5.conf is up-to-date
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    mode: 0644
    owner: root
    group: root
